apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.podInfo.name }}
  {{- with .Values.podLabels }}
  labels:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  containers:
    - name: {{ .Values.podInfo.name }}
      image: {{ .Values.podInfo.image }}
