apiVersion: v1
kind: ConfigMap
metadata:
  name: game-demo
data:
  nginx.conf: |
    proxy_http_version 1.1;
    location /images/ {
        expires 5s;
        root   /usr/share/nginx/html;
        try_files $uri /images/placeholder.jpg;
    }
    error_page   500 502 503 504  /50x.html;
    location /api/catalogue/ { proxy_pass http://catalogue-dev:80/; }
    location /api/user/ { proxy_pass http://user-dev:80/; }
    location /api/cart/ { proxy_pass http://cart-dev:80/; }
    location /api/shipping/ { proxy_pass http://shipping-dev:80/; }
    location /api/payment/ { proxy_pass http://payment-dev:80/; }
    location /health {
            return 200 'OK';
        }
    location /nginx_status {
        stub_status on;
        access_log off;
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo-pod
spec:
  containers:
    - name: demo
      image: centos:7
      command: ["sleep", "100000"]
      volumeMounts:
      - name: config
        mountPath: "/config"
        readOnly: true
  volumes:
    - name: config
      configMap:
        name: game-demo
