apiVersion: v1
kind: Pod
metadata:
  name: cart
  labels:
    app: cart
spec:
  containers:
    - name: cart
      image: 260038077524.dkr.ecr.us-east-1.amazonaws.com/cart:1.0.10
---
apiVersion: v1
kind: Service
metadata:
  name: cart
spec:
  selector:
    app: cart
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080