apiVersion: v1
kind: Pod
metadata:
  name: catalogue
  labels:
    app: catalogue
spec:
  containers:
    - name: catalogue
      image: 739561048503.dkr.ecr.us-east-1.amazonaws.com/catalogue:1.0.5
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
spec:
  selector:
    app: catalogue
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
