apiVersion: v1
kind: Pod
metadata:
  name: shipping
  labels:
    app: shipping
spec:
  containers:
    - name: shipping
      image: 739561048503.dkr.ecr.us-east-1.amazonaws.com/shipping:1.0.8

---
apiVersion: v1
kind: Service
metadata:
  name: shipping
spec:
  selector:
    app: shipping
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080