apiVersion: v1
kind: Pod
metadata:
  name: user
  labels:
    app: user
spec:
  containers:
    - name: user
      image: 739561048503.dkr.ecr.us-east-1.amazonaws.com/user:1.0.7
---
apiVersion: v1
kind: Service
metadata:
  name: user
spec:
  selector:
    app: user
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080